version: '3.8'

services:
  rails: &rails
    working_dir: /myapp
    build:
      context: .
      dockerfile: ./.dockerdev/rails/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      NODE_ENV: ${NODE_ENV:-development}
      DEFAULT_HOST: localhost:3000
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: ''
      REDIS_URL: redis://redis
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3035
    volumes:
      - .:/myapp:cached
      - rails_cache:/myapp/tmp/cache
      - rails_bundle:/bundle
      - rails_node_modules:/myapp/node_modules
      - rails_packs:/myapp/public/packs
      - /myapp/tmp/pids
    ports:
      - '3000:3000'
    depends_on:
      - webpacker
      - mysql
      - redis
    tmpfs:
      - /tmp

  webpacker:
    <<: *rails
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    depends_on: []

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6.0
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  rails_cache:
    driver: local
  rails_bundle:
    driver: local
  rails_node_modules:
    driver: local
  rails_packs:
    driver: local
  mysql_data:
    driver: local
  redis_data:
    driver: local
