default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>

development:
  <<: *default
  database: webapp_development
  username: <%= ENV['MYSQL_USER'] || 'root' %>
  password: <%= ENV['MYSQL_PASS'] || '' %>

test:
  <<: *default
  database: webapp_test
  username: <%= ENV['MYSQL_USER'] || 'root' %>
  password: <%= ENV['MYSQL_PASS'] || '' %>

production:
  <<: *default
  database: webapp_production
  username: <%= ENV['MYSQL_USER'] || 'webapp' %>
  password: <%= ENV['MYSQL_PASS'] || '' %>